[project]
name = "explore-dataset"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "kagglehub>=0.4.3",
    "loguru>=0.7.3",
    "marimo>=0.19.9",
    "polars>=1.38.1",
]
